language: php

php:
  - 5.5
  - 5.6

cache:
    directories:
        - ~/.composer/cache

git:
  submodules: false

before_script:
# webserver
 - sudo apt-get update > /dev/null
 - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
 - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
 - sudo /etc/init.d/apache2 restart

# Symfony
 - cp app/config/parameters.yml.travis app/config/parameters.yml
# - cp .travis-composer-config.json ~/.composer/config.json
 - composer install --no-progress --prefer-dist
 - php app/console doctrine:database:create --env=test
 - php app/console doctrine:schema:create --env=test
 - php app/console doctrine:fixtures:load -n --env=test
 - chmod -R 777 /tmp/cache /tmp/logs

script: bin/phpspec run && bin/behat

after_success:
    - openssl aes-256-cbc -K $encrypted_168c5169b1c4_key -iv $encrypted_168c5169b1c4_iv -in id_rsa.enc -out id_rsa -d
    - bundle install
    - if [[ $TRAVIS_BRANCH = 'master' ]]; then
        bundle exec cap deploy
      fi
