api_login_check:
   path: /api/login_check

spyl_baka:
    resource: "Spyl\Bundle\BakaBundle\Controller\Front\DefaultController"
    type:     annotation
    prefix:   /

spyl_baka_api_manga:
    resource: "Spyl\Bundle\BakaBundle\Controller\Api\MangaController"
    type:     rest
    prefix:   /api/
