Spyl\Bundle\BakaBundle\Model\Manga:
  type: entity
  table: manga
  #repositoryClass: Spyl\Bundle\BakaBundle\Repository\MangaRepository
  fields:
    id:
      type: string
      id: true
    name:
      type: string
      length: 255
    image:
      type: string
      length: 255