Spyl\Bundle\BakaBundle\Model\Manga:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [list, details]
    name:
      expose: true
      groups: [list, details]
    image:
      expose: true
      groups: [list, details]
    contents:
      expose: true
      groups: [details]
